version: "2.1"
services:
  books-ms:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      mysql-docker-container:
        condition: service_healthy
    healthcheck:
      test: "curl -I books-ms:3002/books-ms/ --fail"
      interval: 20s
      retries: 10

  mysql-docker-container:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: books-db
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"